from datetime import datetime


MONDAY = "2026-04-27"


def replan_calendar(intent, skill_outputs):
    dining = skill_outputs["dining"]["recommendations"]
    dinner = next(item for item in dining if item["meal_period"] == "dinner")
    lunch = next(item for item in dining if item["meal_period"] == "lunch")

    blocks = [
        {
            "id": "block_class_mon",
            "title": "Class block",
            "type": "class",
            "start": f"{MONDAY}T10:00:00",
            "end": f"{MONDAY}T14:00:00",
            "location": "UCLA campus",
            "reason": "This fixed class block is protected before meals, recovery, and study work are placed around it.",
            "scores": {"time": 0.98, "health": 0.66, "energy": 0.70, "sustainability": 0.72, "carbon": 0.84},
            "carbon": {"estimated_co2e_kg": 0.1, "baseline_co2e_kg": 0.1, "delta_co2e_kg": 0.0, "category": "calendar"},
            "skills_used": ["calendar"],
            "data_sources": ["user_schedule"],
        },
        {
            "id": "block_walk_mon",
            "title": "Recovery walk",
            "type": "recovery",
            "start": f"{MONDAY}T14:15:00",
            "end": f"{MONDAY}T14:45:00",
            "location": "Bruin Walk",
            "reason": "A short walk after class creates an energy reset without adding more transportation emissions after the emergency Uber.",
            "scores": {"time": 0.88, "health": 0.84, "energy": 0.80, "sustainability": 0.90, "carbon": 0.96},
            "carbon": {"estimated_co2e_kg": 0.0, "baseline_co2e_kg": 0.4, "delta_co2e_kg": -0.4, "category": "transportation"},
            "skills_used": ["calendar", "transportation", "energy", "health", "sustainability_carbon"],
            "data_sources": ["carbon_factors", "user_schedule"],
        },
        {
            "id": "block_dinner_mon",
            "title": f"Low-carbon dinner at {dinner['dining_hall']}",
            "type": "meal",
            "start": f"{MONDAY}T18:30:00",
            "end": f"{MONDAY}T19:15:00",
            "location": dinner["dining_hall"],
            "reason": "The emergency Uber raised today's transportation impact, so dinner shifts toward a plant-forward option while preserving protein and evening energy.",
            "scores": {"time": 0.86, "health": dinner["scores"]["health"], "energy": dinner["scores"]["energy"], "sustainability": dinner["scores"]["sustainability"], "carbon": dinner["scores"]["carbon"]},
            "carbon": {"estimated_co2e_kg": dinner["carbon"]["estimated_co2e_kg"], "baseline_co2e_kg": 1.8, "delta_co2e_kg": -1.1, "category": "dining"},
            "skills_used": ["dining", "sustainability_carbon", "health", "energy", "calendar"],
            "data_sources": ["ucla_dining_mock", "carbon_factors", "local_planner"],
        },
        {
            "id": "block_study_mon",
            "title": "Homework deep work",
            "type": "study",
            "start": f"{MONDAY}T19:45:00",
            "end": f"{MONDAY}T21:15:00",
            "location": "Powell Library",
            "reason": "Homework stays tonight, but starts after dinner and a transition buffer so the plan does not stack heavy work immediately after class.",
            "scores": {"time": 0.89, "health": 0.72, "energy": 0.78, "sustainability": 0.80, "carbon": 0.88},
            "carbon": {"estimated_co2e_kg": 0.05, "baseline_co2e_kg": 0.20, "delta_co2e_kg": -0.15, "category": "study"},
            "skills_used": ["study", "calendar", "energy", "explanation"],
            "data_sources": ["user_schedule", "local_planner"],
        },
        {
            "id": "block_winddown_mon",
            "title": "Sleep wind-down",
            "type": "rest",
            "start": f"{MONDAY}T22:30:00",
            "end": f"{MONDAY}T23:00:00",
            "location": "Dorm",
            "reason": "A short wind-down block protects recovery after a day with class, emergency travel, and homework.",
            "scores": {"time": 0.82, "health": 0.88, "energy": 0.86, "sustainability": 0.74, "carbon": 0.90},
            "carbon": {"estimated_co2e_kg": 0.0, "baseline_co2e_kg": 0.0, "delta_co2e_kg": 0.0, "category": "rest"},
            "skills_used": ["health", "energy", "calendar"],
            "data_sources": ["local_planner"],
        },
        {
            "id": "block_transit_tue",
            "title": "Transit-first commute",
            "type": "commute",
            "start": "2026-04-28T09:20:00",
            "end": "2026-04-28T09:50:00",
            "location": "Big Blue Bus",
            "reason": "Tomorrow's route uses transit where the schedule allows, compensating for today's ride-share without creating a rushed morning.",
            "scores": {"time": 0.78, "health": 0.70, "energy": 0.74, "sustainability": 0.91, "carbon": 0.93},
            "carbon": {"estimated_co2e_kg": 0.3, "baseline_co2e_kg": 1.2, "delta_co2e_kg": -0.9, "category": "transportation"},
            "skills_used": ["transportation", "sustainability_carbon", "calendar"],
            "data_sources": ["carbon_factors", "user_schedule"],
        },
        {
            "id": "block_lunch_tue",
            "title": "Plant-forward lunch",
            "type": "meal",
            "start": "2026-04-28T12:00:00",
            "end": "2026-04-28T12:45:00",
            "location": lunch["dining_hall"],
            "reason": "A lighter lunch keeps afternoon energy steady while continuing the lower-carbon dining pattern.",
            "scores": {"time": 0.84, "health": lunch["scores"]["health"], "energy": lunch["scores"]["energy"], "sustainability": lunch["scores"]["sustainability"], "carbon": lunch["scores"]["carbon"]},
            "carbon": {"estimated_co2e_kg": lunch["carbon"]["estimated_co2e_kg"], "baseline_co2e_kg": 1.5, "delta_co2e_kg": -0.9, "category": "dining"},
            "skills_used": ["dining", "health", "energy", "sustainability_carbon"],
            "data_sources": ["ucla_dining_mock", "carbon_factors"],
        },
        {
            "id": "block_review_wed",
            "title": "Review sprint",
            "type": "study",
            "start": "2026-04-29T15:00:00",
            "end": "2026-04-29T16:15:00",
            "location": "Study commons",
            "reason": "A midweek review prevents Monday night from becoming the only academic catch-up slot.",
            "scores": {"time": 0.84, "health": 0.70, "energy": 0.79, "sustainability": 0.76, "carbon": 0.86},
            "carbon": {"estimated_co2e_kg": 0.05, "baseline_co2e_kg": 0.05, "delta_co2e_kg": 0.0, "category": "study"},
            "skills_used": ["study", "calendar", "energy"],
            "data_sources": ["user_schedule"],
        },
        {
            "id": "block_workout_thu",
            "title": "Light workout",
            "type": "recovery",
            "start": "2026-04-30T16:00:00",
            "end": "2026-04-30T17:00:00",
            "location": "John Wooden Center",
            "reason": "A light workout lands in a low-conflict window and supports health without making the week feel overpacked.",
            "scores": {"time": 0.80, "health": 0.92, "energy": 0.75, "sustainability": 0.78, "carbon": 0.88},
            "carbon": {"estimated_co2e_kg": 0.02, "baseline_co2e_kg": 0.02, "delta_co2e_kg": 0.0, "category": "health"},
            "skills_used": ["health", "energy", "calendar"],
            "data_sources": ["local_planner"],
        },
    ]

    return blocks
